player removeItem "HandGrenade";
player removeItem "HandGrenade";
player removeItem "ACE_M84";
player removeItem "SmokeShell";
player removeItem "SmokeShell";
player removeItem "SmokeShellRed";
player removeItem "SmokeShellGreen";
removeAllItems player;
removeAllAssignedItems player;
player addItemToUniform "ACE_EarPlugs";
player addItemToUniform "ACE_MapTools";
for "_i" from 1 to 2 do {player addItemToUniform "ACE_CableTie";};
player addItemToUniform "ACE_Flashlight_XL50";
for "_i" from 1 to 2 do {player addItemToUniform "ACE_tourniquet";};
for "_i" from 1 to 2 do {player addItemToVest "ACE_morphine";};
for "_i" from 1 to 2 do {player addItemToVest "ACE_epinephrine";};
for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {player addItemToVest "SmokeShell";};
player addItemToVest "SmokeShellRed";
player addItemToVest "SmokeShellGreen";
for "_i" from 1 to 20 do {player addItemToBackpack "ACE_elasticBandage";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_salineIV_500";};
player addItemToBackpack "ACE_Clacker";
player addItemToBackpack "MineDetector";
player addItemToBackpack "ACE_DefusalKit";
player addItemToBackpack "ACE_SpraypaintRed";
player addItemToBackpack "ACE_SpraypaintBlack";
player addItemToBackpack "ACE_VMM3";
player addWeapon "Binocular";
player linkItem "ItemMap";
player linkItem "ItemCompass";
player linkItem "tf_microdagr";
player linkItem "tf_anprc152";
player linkItem "ItemGPS";
[] call life_fnc_saveGear;
hint format ["%1 you have loaded the E.O.D Loadout",player ]