player removeItem "HandGrenade";
player removeItem "HandGrenade";
player removeItem "ACE_M84";
player removeItem "SmokeShell";
player removeItem "SmokeShell";
player removeItem "SmokeShellRed";
player removeItem "SmokeShellGreen";
removeAllItems player;
removeAllAssignedItems player;
for "_i" from 1 to 2 do {player addItemToUniform "ACE_tourniquet";};
player addItemToUniform "ACE_Flashlight_XL50";
player addItemToUniform "ACE_EarPlugs";
player addItemToUniform "ACE_MapTools";
for "_i" from 1 to 2 do {player addItemToUniform "ACE_CableTie";};
for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {player addItemToVest "SmokeShell";};
player addItemToVest "SmokeShellRed";
player addItemToVest "SmokeShellGreen";
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 30 do {player addItemToBackpack "ACE_elasticBandage";};
player addWeapon "Binocular";
player linkItem "ItemMap";
player linkItem "ItemCompass";
player linkItem "ItemWatch";
player linkItem "TFAR_anprc152";
player linkItem "B_UavTerminal";
[] call life_fnc_saveGear;
hint format ["%1 you have loaded the JTAC/Radioman Loadout",player ]