removeAllItems player;
removeAllAssignedItems player;
for "_i" from 1 to 2 do {player addItemToUniform "ACE_CableTie";};
player addItemToUniform "ACE_EarPlugs";
player addItemToUniform "ACE_Flashlight_XL50";
player addItemToUniform "ACE_MapTools";
for "_i" from 1 to 4 do {player addItemToUniform "ACE_tourniquet";};
player addItemToUniform "ACE_RangeCard";
player addItemToUniform "ACE_DAGR";
player addItemToUniform "ACE_ATragMX";
player addItemToUniform "ACE_Kestrel4500";
for "_i" from 1 to 4 do {player addItemToBackpack "ACE_epinephrine";};
player addItemToBackpack "ACE_surgicalKit";
for "_i" from 1 to 5 do {player addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_salineIV";};
player addItemToBackpack "ACE_personalAidKit";
for "_i" from 1 to 6 do {player addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_IR_Strobe_Item";};
for "_i" from 1 to 50 do {player addItemToBackpack "ACE_elasticBandage";};
player addItemToBackpack "ACE_EntrenchingTool";
for "_i" from 1 to 2 do {player addItemToBackpack "SmokeShell";};
player addItemToBackpack "SmokeShellRed";
player addItemToBackpack "SmokeShellGreen";
player addItemToBackpack "rhs_mag_m67";
player addWeapon "ACE_Vector";
player linkItem "ItemMap";
player linkItem "ItemCompass";
player linkItem "tf_microdagr";
player linkItem "tf_anprc152_9";
player linkItem "ItemGPS";
player linkItem "TRYK_G_Shades_Black_NV";
[] call life_fnc_saveGear;
hint format ["%1 you have loaded the Sniper Loadout",player ]