removeAllItems this;
removeAllAssignedItems this;
this addItemToUniform "ACE_Kestrel4500";
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_MapTools";
this addItemToUniform "ACE_DAGR";
this addItemToUniform "ACE_ATragMX";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_RangeCard";
for "_i" from 1 to 4 do {this addItemToVest "ACE_CableTie";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShellRed";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShellGreen";};
for "_i" from 1 to 2 do {this addItemToBackpack "ACE_tourniquet";};
this addItemToBackpack "ACE_SpottingScope";
this addItemToBackpack "ACE_surgicalKit";
for "_i" from 1 to 2 do {this addItemToBackpack "ACE_salineIV";};
for "_i" from 1 to 2 do {this addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_packingBandage";};
for "_i" from 1 to 6 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 6 do {this addItemToBackpack "ACE_epinephrine";};
this addItemToBackpack "ACE_Banana";
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_elasticBandage";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_quikclot";};
for "_i" from 1 to 4 do {this addItemToBackpack "ACE_IR_Strobe_Item";};
this addItemToBackpack "NVGoggles_OPFOR";
this addWeapon "ACE_VectorDay";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "tf_microdagr";
this linkItem "tf_anprc152_1";
this linkItem "B_UavTerminal";
[] call life_fnc_saveGear;